language: go

go_import_path: 4d63.com/uuid

go:
  - tip

os:
  - linux

script:
  - go vet
  - go test . -coverprofile=coverage-1.txt
  - go test ./uuidv1 -coverprofile=coverage-2.txt

after_success:
  - cat coverage-*.txt > coverage.txt
  - bash <(curl -s https://codecov.io/bash)
